<?php
return [
    "Contabilidad y Auditoría",
    "Derecho",
    "Ingeniería Civil",
    "Medicina",
    "Arquitectura",
    "Marketing",
    "Ingeniería Mecánica",
    "Educación Inicial",
    "Ingeniería Electrónica",
    "Comunicación Social",
    "Turismo y Hotelería",
    "Trabajo Social",
    "Ingeniería Industrial",
    "Enfermería",
    "Biología",
    "Gastronomía",
    "Diseño Gráfico",
    "Ingeniería Ambiental",
    "Ingeniería Agronómica",
    "Nutrición",
    "Finanzas",
    "Ciencias Políticas",
    "Sociología",
    "Filosofía",
    "Periodismo",
    "Relaciones Internacionales",
    "Ingeniería en Software",
    "Matemáticas",
    "Física",
    "Arte y Diseño"
];
